version: "3.4"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pageboy
      MYSQL_USER: pageboy
      MYSQL_PASSWORD: pageboy
      MYSQL_ROOT_PASSWORD: pageboy
    volumes:
      - ./containers/mysql/conf.d:/etc/mysql/conf.d
  postgres:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pageboy
      POSTGRES_USER: pageboy
      POSTGRES_PASSWORD: pageboy
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: hXUeLZvM4p3r2XeBG
