version: "3.4"

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pageboy
      MYSQL_USER: pageboy
      MYSQL_PASSWORD: pageboy
      MYSQL_ROOT_PASSWORD: pageboy
    volumes:
      - ./containers/mysql/conf.d:/etc/mysql/conf.d
