version: 2.1

default: &default
  docker:
    - image: circleci/golang:1.13
    - image: circleci/mysql:8.0
      environment:
        MYSQL_DATABASE: magion
        MYSQL_USER: magion
        MYSQL_PASSWORD: magion
        MYSQL_ROOT_PASSWORD: magion

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - run: make build
  lint:
    <<: *default
    steps:
      - checkout
      - run: make lint
  test:
    <<: *default
    steps:
      - checkout
      - run:
        name: Waiting for MySQL to be ready
        command: |
          for i in `seq 1 10`;
          do
            nc -z localhost 3306 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for MySQL && exit 1
      - run: make test

workflows:
  version: 2
  general:
    jobs:
      - build
      - lint
      - test
